branch-defaults:
  master:
    environment: live
global:
  application_name: embedded-sample-app
  default_ec2_keyname: ec2
  default_platform: 64bit Amazon Linux 2016.09 v2.3.3 running Ruby 2.3 (Puma)
  default_region: eu-west-1
  profile: eb-cli
  sc: git
